from _typeshed import Incomplete
from collections.abc import Mapping
from typing import Final

from .auxfuncs import isintent_dict as isintent_dict

__version__: Final[str] = ...
f2py_version: Final = "See `f2py -v`"

options: Final[dict[str, bool]]

fgetdims1: Final[str] = ...
fgetdims2: Final[str] = ...
fgetdims2_sa: Final[str] = ...

def findf90modules(m: Mapping[str, Incomplete]) -> list[dict[str, Incomplete]]: ...
def buildhooks(pymod: Mapping[str, Incomplete]) -> dict[str, Incomplete]: ...
