name: Feature request
description: Suggest an improvement or propose a new feature.
title: "<Please write a comprehensive title>"
labels: ["stubs: Enhancement"]
body:
- type: markdown
  attributes:
    value: >
      If you're looking to request a new feature or change in functionality,
      including adding or changing the meaning of arguments to an existing
      function.

- type: textarea
  attributes:
    label: "Please describe the feature or change you would like to see:"
  validations:
    required: true
