from typing import Final
from typing_extensions import LiteralString

__version__: Final[LiteralString] = ...
version: Final[LiteralString] = ...
full_version: Final[LiteralString] = ...
short_version: Final[LiteralString] = ...

release: Final[bool] = ...
git_revision: Final[LiteralString] = ...
