from typing import Final

import numpy as np
from numpy._typing._ufunc import _gufunc_1_1, _gufunc_1_2, _gufunc_2_1

__version__: Final[str] = ...
_ilp64: Final[bool] = ...

###
# 1 -> 1

# (m,m) -> ()
det: Final[_gufunc_1_1] = ...
# (m,m) -> (m)
cholesky_lo: Final[_gufunc_1_1] = ...
cholesky_up: Final[_gufunc_1_1] = ...
eigvals: Final[_gufunc_1_1] = ...
eigvalsh_lo: Final[_gufunc_1_1] = ...
eigvalsh_up: Final[_gufunc_1_1] = ...
# (m,m) -> (m,m)
inv: Final[_gufunc_1_1] = ...
# (m,n) -> (p)
qr_r_raw: Final[_gufunc_1_1] = ...
svd: Final[_gufunc_1_1] = ...

###
# 1 -> 2

# (m,m) -> (), ()
slogdet: Final[_gufunc_1_2] = ...
# (m,m) -> (m), (m,m)
eig: Final[_gufunc_1_2] = ...
eigh_lo: Final[_gufunc_1_2] = ...
eigh_up: Final[_gufunc_1_2] = ...

###
# 2 -> 1

# (m,n), (n) -> (m,m)
qr_complete: Final[_gufunc_2_1] = ...
# (m,n), (k) -> (m,k)
qr_reduced: Final[_gufunc_2_1] = ...
# (m,m), (m,n) -> (m,n)
solve: Final[_gufunc_2_1] = ...
# (m,m), (m) -> (m)
solve1: Final[_gufunc_2_1] = ...

###
# 1 -> 3

# (m,n) -> (m,m), (p), (n,n)
svd_f: Final[np.ufunc] = ...
# (m,n) -> (m,p), (p), (p,n)
svd_s: Final[np.ufunc] = ...

###
# 3 -> 4

# (m,n), (m,k), () -> (n,k), (k), (), (p)
lstsq: Final[np.ufunc] = ...
