from typing import (
    Any,
    NoReturn,
    Protocol,
    TypeAlias,
    final,
    overload,
    type_check_only,
)
from typing_extensions import TypeVar

import numpy as np

from . import NBitBase
from ._array_like import NDArray
from ._nbit import _NBitInt
from ._nested_sequence import _NestedSequence
from ._scalars import _BoolLike_co, _IntLike_co, _NumberLike_co

_T1 = TypeVar("_T1")
_T1_contra = TypeVar("_T1_contra", contravariant=True)
_T2_contra = TypeVar("_T2_contra", contravariant=True)

_2Tuple: TypeAlias = tuple[_T1, _T1]

_NBit1 = TypeVar("_NBit1", bound=NBitBase)
_NBit2 = TypeVar("_NBit2", bound=NBitBase)

_IntType = TypeVar("_IntType", bound=np.integer)
_FloatType = TypeVar("_FloatType", bound=np.floating)
_NumberType = TypeVar("_NumberType", bound=np.number)
_GenericType_co = TypeVar("_GenericType_co", covariant=True, bound=np.generic)

@type_check_only
class _BoolOp(Protocol[_GenericType_co]):
    @overload
    def __call__(self, other: _BoolLike_co, /) -> _GenericType_co: ...
    @overload  # platform dependent
    def __call__(self, other: int, /) -> np.int_: ...
    @overload
    def __call__(self, other: float, /) -> np.float64: ...
    @overload
    def __call__(self, other: complex, /) -> np.complex128: ...
    @overload
    def __call__(self, other: _NumberType, /) -> _NumberType: ...

@type_check_only
class _BoolBitOp(Protocol[_GenericType_co]):
    @overload
    def __call__(self, other: _BoolLike_co, /) -> _GenericType_co: ...
    @overload  # platform dependent
    def __call__(self, other: int, /) -> np.int_: ...
    @overload
    def __call__(self, other: _IntType, /) -> _IntType: ...

@type_check_only
class _BoolSub(Protocol):
    # Note that `other: bool` is absent here
    @overload
    def __call__(self, other: bool, /) -> NoReturn: ...
    @overload  # platform dependent
    def __call__(self, other: int, /) -> np.int_: ...
    @overload
    def __call__(self, other: float, /) -> np.float64: ...
    @overload
    def __call__(self, other: complex, /) -> np.complex128: ...
    @overload
    def __call__(self, other: _NumberType, /) -> _NumberType: ...

@type_check_only
class _BoolTrueDiv(Protocol):
    @overload
    def __call__(self, other: float | _IntLike_co, /) -> np.float64: ...
    @overload
    def __call__(self, other: complex, /) -> np.complex128: ...
    @overload
    def __call__(self, other: _NumberType, /) -> _NumberType: ...

@type_check_only
class _BoolMod(Protocol):
    @overload
    def __call__(self, other: _BoolLike_co, /) -> np.int8: ...
    @overload  # platform dependent
    def __call__(self, other: int, /) -> np.int_: ...
    @overload
    def __call__(self, other: float, /) -> np.float64: ...
    @overload
    def __call__(self, other: _IntType, /) -> _IntType: ...
    @overload
    def __call__(self, other: _FloatType, /) -> _FloatType: ...

@type_check_only
class _BoolDivMod(Protocol):
    @overload
    def __call__(self, other: _BoolLike_co, /) -> _2Tuple[np.int8]: ...
    @overload  # platform dependent
    def __call__(self, other: int, /) -> _2Tuple[np.int_]: ...
    @overload
    def __call__(self, other: float, /) -> _2Tuple[np.float64]: ...
    @overload
    def __call__(self, other: _IntType, /) -> _2Tuple[_IntType]: ...
    @overload
    def __call__(self, other: _FloatType, /) -> _2Tuple[_FloatType]: ...

@type_check_only
class _IntTrueDiv(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> np.floating[_NBit1]: ...
    @overload
    def __call__(self, other: int, /) -> np.floating[_NBit1] | np.floating[_NBitInt]: ...
    @overload
    def __call__(self, other: float, /) -> np.floating[_NBit1] | np.float64: ...
    @overload
    def __call__(self, other: complex, /) -> np.complexfloating[_NBit1] | np.complex128: ...
    @overload
    def __call__(self, other: np.integer[_NBit2], /) -> np.floating[_NBit1] | np.floating[_NBit2]: ...

@type_check_only
class _UnsignedIntOp(Protocol[_NBit1]):
    # NOTE: `uint64 + np.signedinteger -> np.float64`
    @overload
    def __call__(self, other: int, /) -> np.unsignedinteger[_NBit1]: ...
    @overload
    def __call__(self, other: float, /) -> np.float64: ...
    @overload
    def __call__(self, other: complex, /) -> np.complex128: ...
    @overload
    def __call__(self, other: np.unsignedinteger[_NBit2], /) -> np.unsignedinteger[_NBit1] | np.unsignedinteger[_NBit2]: ...
    @overload
    def __call__(self, other: np.signedinteger, /) -> Any: ...

@type_check_only
class _UnsignedIntBitOp(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> np.unsignedinteger[_NBit1]: ...
    @overload
    def __call__(self, other: int, /) -> np.signedinteger[Any]: ...
    @overload
    def __call__(self, other: np.signedinteger[Any], /) -> np.signedinteger[Any]: ...
    @overload
    def __call__(self, other: np.unsignedinteger[_NBit2], /) -> np.unsignedinteger[_NBit1] | np.unsignedinteger[_NBit2]: ...

@type_check_only
class _UnsignedIntMod(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> np.unsignedinteger[_NBit1]: ...
    @overload
    def __call__(self, other: int | np.signedinteger[Any], /) -> Any: ...
    @overload
    def __call__(self, other: float, /) -> np.floating[_NBit1] | np.float64: ...
    @overload
    def __call__(self, other: np.unsignedinteger[_NBit2], /) -> np.unsignedinteger[_NBit1] | np.unsignedinteger[_NBit2]: ...

@type_check_only
class _UnsignedIntDivMod(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> _2Tuple[np.signedinteger[_NBit1]]: ...
    @overload
    def __call__(self, other: int | np.signedinteger[Any], /) -> _2Tuple[Any]: ...
    @overload
    def __call__(self, other: float, /) -> _2Tuple[np.floating[_NBit1]] | _2Tuple[np.float64]: ...
    @overload
    def __call__(
        self, other: np.unsignedinteger[_NBit2], /
    ) -> _2Tuple[np.unsignedinteger[_NBit1]] | _2Tuple[np.unsignedinteger[_NBit2]]: ...

@type_check_only
class _SignedIntOp(Protocol[_NBit1]):
    @overload
    def __call__(self, other: int, /) -> np.signedinteger[_NBit1]: ...
    @overload
    def __call__(self, other: float, /) -> np.float64: ...
    @overload
    def __call__(self, other: complex, /) -> np.complex128: ...
    @overload
    def __call__(self, other: np.signedinteger[_NBit2], /) -> np.signedinteger[_NBit1] | np.signedinteger[_NBit2]: ...

@type_check_only
class _SignedIntBitOp(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> np.signedinteger[_NBit1]: ...
    @overload
    def __call__(self, other: int, /) -> np.signedinteger[_NBit1] | np.int_: ...
    @overload
    def __call__(self, other: np.signedinteger[_NBit2], /) -> np.signedinteger[_NBit1] | np.signedinteger[_NBit2]: ...

@type_check_only
class _SignedIntMod(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> np.signedinteger[_NBit1]: ...
    @overload
    def __call__(self, other: int, /) -> np.signedinteger[_NBit1] | np.int_: ...
    @overload
    def __call__(self, other: float, /) -> np.floating[_NBit1] | np.float64: ...
    @overload
    def __call__(self, other: np.signedinteger[_NBit2], /) -> np.signedinteger[_NBit1] | np.signedinteger[_NBit2]: ...

@type_check_only
class _SignedIntDivMod(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> _2Tuple[np.signedinteger[_NBit1]]: ...
    @overload
    def __call__(self, other: int, /) -> _2Tuple[np.signedinteger[_NBit1]] | _2Tuple[np.int_]: ...
    @overload
    def __call__(self, other: float, /) -> _2Tuple[np.floating[_NBit1]] | _2Tuple[np.float64]: ...
    @overload
    def __call__(
        self, other: np.signedinteger[_NBit2], /
    ) -> _2Tuple[np.signedinteger[_NBit1]] | _2Tuple[np.signedinteger[_NBit2]]: ...

@type_check_only
class _FloatOp(Protocol[_NBit1]):
    @overload
    def __call__(self, other: int, /) -> np.floating[_NBit1]: ...
    @overload
    def __call__(self, other: float, /) -> np.floating[_NBit1] | np.float64: ...
    @overload
    def __call__(self, other: complex, /) -> np.complexfloating[_NBit1] | np.complex128: ...
    @overload
    def __call__(self, other: np.integer[_NBit2] | np.floating[_NBit2], /) -> np.floating[_NBit1] | np.floating[_NBit2]: ...

@type_check_only
class _FloatMod(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> np.floating[_NBit1]: ...
    @overload
    def __call__(self, other: int, /) -> np.floating[_NBit1] | np.floating[_NBitInt]: ...
    @overload
    def __call__(self, other: float, /) -> np.floating[_NBit1] | np.float64: ...
    @overload
    def __call__(self, other: np.integer[_NBit2] | np.floating[_NBit2], /) -> np.floating[_NBit1] | np.floating[_NBit2]: ...

class _FloatDivMod(Protocol[_NBit1]):
    @overload
    def __call__(self, other: bool, /) -> _2Tuple[np.floating[_NBit1]]: ...
    @overload
    def __call__(self, other: int, /) -> _2Tuple[np.floating[_NBit1]] | _2Tuple[np.floating[_NBitInt]]: ...
    @overload
    def __call__(self, other: float, /) -> _2Tuple[np.floating[_NBit1]] | _2Tuple[np.float64]: ...
    @overload
    def __call__(
        self, other: np.integer[_NBit2] | np.floating[_NBit2], /
    ) -> _2Tuple[np.floating[_NBit1]] | _2Tuple[np.floating[_NBit2]]: ...

@type_check_only
class _NumberOp(Protocol):
    def __call__(self, other: _NumberLike_co, /) -> Any: ...

@final
@type_check_only
class _SupportsLT(Protocol):
    def __lt__(self, other: Any, /) -> Any: ...

@final
@type_check_only
class _SupportsLE(Protocol):
    def __le__(self, other: Any, /) -> Any: ...

@final
@type_check_only
class _SupportsGT(Protocol):
    def __gt__(self, other: Any, /) -> Any: ...

@final
@type_check_only
class _SupportsGE(Protocol):
    def __ge__(self, other: Any, /) -> Any: ...

@final
@type_check_only
class _ComparisonOpLT(Protocol[_T1_contra, _T2_contra]):
    @overload
    def __call__(self, other: _T1_contra, /) -> np.bool: ...
    @overload
    def __call__(self, other: _T2_contra, /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _NestedSequence[_SupportsGT], /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _SupportsGT, /) -> np.bool: ...

@final
@type_check_only
class _ComparisonOpLE(Protocol[_T1_contra, _T2_contra]):
    @overload
    def __call__(self, other: _T1_contra, /) -> np.bool: ...
    @overload
    def __call__(self, other: _T2_contra, /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _NestedSequence[_SupportsGE], /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _SupportsGE, /) -> np.bool: ...

@final
@type_check_only
class _ComparisonOpGT(Protocol[_T1_contra, _T2_contra]):
    @overload
    def __call__(self, other: _T1_contra, /) -> np.bool: ...
    @overload
    def __call__(self, other: _T2_contra, /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _NestedSequence[_SupportsLT], /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _SupportsLT, /) -> np.bool: ...

@final
@type_check_only
class _ComparisonOpGE(Protocol[_T1_contra, _T2_contra]):
    @overload
    def __call__(self, other: _T1_contra, /) -> np.bool: ...
    @overload
    def __call__(self, other: _T2_contra, /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _NestedSequence[_SupportsGT], /) -> NDArray[np.bool]: ...
    @overload
    def __call__(self, other: _SupportsGT, /) -> np.bool: ...
