name: deploy docs

on:
  push:
    branches: [main]
    paths:
    - "docs/**"
    - ".github/workflows/docs.yml"
    - "CONTRIBUTING.md"
    - "mkdocs.yml"
    - "uv.lock"
  release:
    types: [released]
  workflow_dispatch:

permissions:
  contents: write

env:
  UV_FROZEN: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0

    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - uses: astral-sh/setup-uv@v6.6.0

    - name: mkdocs gh-deploy
      run: uv run --only-group=docs mkdocs gh-deploy --force
