name: deploy docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
      - "CONTRIBUTING.md"

permissions:
  contents: write

env:
  UV_FROZEN: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: mkdocs gh-deploy
        run: uv run --only-group=docs mkdocs gh-deploy --force
