name: Renovate
permissions:
  contents: read

on:
  schedule:
  - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - uses: renovatebot/github-action@v43.0.5
      with:
        configurationFile: .github/renovate.json5
        token: ${{ secrets.RENOVATE_TOKEN }}
      env:
        LOG_LEVEL: "debug"
