name: Renovate
permissions:
  contents: read

on:
  schedule:
  - cron: "0 0/1 * * *" # every hour
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - uses: renovatebot/github-action@v43.0.6
      with:
        configurationFile: .github/renovate-config.json
        token: ${{ secrets.RENOVATE_TOKEN }}
